name: Build the deb

on:
  workflow_dispatch:
    inputs:
      uyou_version:
      app_name:
        description: "Name deb"
        default: "Hiepvk"
        required: true
        type: string
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout chrisharper22/sdks
        uses: actions/checkout@main
        with:
          repository: chrisharper22/sdks
          ref: main
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks
          
      - name: Checkout PoomSmart/YouTubeHeader
        uses: actions/checkout@main
        with:
          repository: PoomSmart/YouTubeHeader
          ref: main
          path: Tweaks/YouTubeHeader

      - name: Build Package 
        run: |
          brew install make xz ldid 
          export THEOS=theos
          gmake clean package FINALPACKAGE=1
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload a Build Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ inputs.app_name }}
          path: packages/*.deb
