name: pyzule

on:
  workflow_dispatch:


jobs:
  build:
    name: pyzule
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          repository: hiepvk/pyzule
          ref: main

      - name: pyzule install
        run: |
          bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

      - name: Check pyzule
        run: |
          pyzule --help
          ls
          mkdir ipa
