name: Pyzule

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct URL to the decrypted App ipa."
        default: ""
        required: true
        type: string
      tweaks:
        description: "tweaks"
        default: "tweaks/"
        required: true
        type: string
      ipa_name:
        description: "Name App"
        default: "NameApp"
        required: true
        type: string


jobs:
  build:
    name: Pyzule run
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          repository: hiepvk/pyzu
          ref: main

      - name: pyzule install
        run: |
          mkdir ipa && mkdir build
          bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

      - name: Download ipa
        id: download_ipa
        run: |
          wget "$IPA_URL" --no-verbose -O ipa/app.ipa
        env:
          IPA_URL: ${{ inputs.ipa_url }}

      - name: Inject
        run: |
          pyzule -i ipa/app.ipa -f ${{ inputs.tweaks }} -u -w -s -o build/${{ inputs.ipa_name }}.ipa

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ inputs.ipa_name }}
          path: build/${{ inputs.ipa_name }}.ipa
