name: pyzule

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct URL to the decrypted App ipa."
        default: "https://dl.dropboxusercontent.com/scl/fi/7ldc3wdq1ootbmne3tmjl/ytb-19.10.5.ipa?rlkey=kvmtrtx1b8xnyz96598v68ya6&dl=0"
        required: true
        type: string


jobs:
  build:
    name: pyzule
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          repository: hiepvk/pyzule
          ref: main

      - name: pyzule install
        run: |
          bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

      - name: Download ipa
        id: download_ipa
        run: |
          wget "$IPA_URL" --no-verbose -O ipa/app.ipa
        env:
          IPA_URL: ${{ inputs.ipa_url }}
      - name: Check pyzule
        run: |
          pyzule --help
          mkdir build
          ls
